title: getting-started-freecad
hero_image: images/banner.png
description: getting-started-freecad description
version: 4
listed: false
copyedit: false
last_tested: "2019-03-01"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
