---
title: Make a dice with FreeCAD
hero_image: images/banner.png
description: Use FreeCAD to design a dice you can 3D print
version: 4
listed: true
copyedit: true
last_tested: '2019-06-17'
steps:
- title: Introduction
- title: Model a cube
- title: Round the cube's edges
  completion:
  - engaged
- title: Add construction geometry
- title: Draw dots
- title: Create pockets
- title: Export your dice
- title: Print the dice
  completion:
  - internal
  completion:
  - external